### ISSUE TITLE
support docker compose

### ISSUE THREAD

**Issue by miltongz** [simbleau/cddns#29]
```
version: '3.3'
services:
    cddns:
        environment:
            - CDDNS_VERIFY_TOKEN='<YOUR_CLOUDFLARE_TOKEN>'
        volumes:
            - '/<host_path>/inventory.yaml:/inventory.yaml'
        image: 'simbleau/cddns:latest'
```
